apimServiceName: test-apim-100
namedValues:
  - name: plainvalue
    properties:
      displayName: plainvalue
      value: "Hello welcome to Prod"
  - name: secret
    properties:
      displayName: secret
      value: "PRODsecret"
  - name: dev-apim-func-01
    properties:
      displayName: dev-apim-func-01
      value: "Iv8Fr8LZVg7lyTyNw8kPXZ2uhkZTV9kY12vqRenN3h2oAzFuiX9Bxw=="
loggers:
diagnostics:
backends:
  - name: dev-apim-func-01 #from fa
    properties:
      url: "https://test-apim-func-01-ayhcbyd3bxesg0c9.canadacentral-01.azurewebsites.net/api"
      resourceId: "https://management.azure.com/subscriptions/ccaf9917-81ae-4a91-8352-8b2ecdeda64e/resourceGroups/apim-rg/providers/Microsoft.Web/sites/test-apim-func-01" #to fa
apis:
