apimServiceName: prod-apim-cicd
namedValues:
  - name: plainvalue
    properties:
      displayName: plainvalue
      value: "https://www.prod.search2.com"
  - name: secret
    properties:
      displayName: secret
      value: "PRODsecret"
  - name: apim-function-001-key
    properties:
      displayName: apim-function-001-key
      value: "pwKT3IwuFr06WxMc6k7QgQWI98ixhRUnQPVn6GGSOMQNAzFu2l5-vA=="
  - name: Logger-Credentials-AppInsights
    properties:
      displayName: Logger-Credentials-AppInsights
      value: "894a16e1-bc04-414e-9ec3-d21317b5da5c"
loggers:
  - name: demo-appinsight
      properties:
        loggerType: applicationInsights
        description: prod application insights
        resourceId: "/subscriptions/ccaf9917-81ae-4a91-8352-8b2ecdeda64e/resourceGroups/apim-rg/providers/microsoft.insights/components/demo-appinsights-prod"
        credentials:
          instrumentationKey: "{{ Logger-Credentials-AppInsights }}"
        isBuffered: true
diagnostics:
backends:
  - name: apim-function-001 #from fa
    properties:
      url: "https://demo-func-prod-bzf0a4c8dyexhegt.canadacentral-01.azurewebsites.net/api"
      resourceId: "https://management.azure.com/subscriptions/ccaf9917-81ae-4a91-8352-8b2ecdeda64e/resourceGroups/demo-func-PROD_group/providers/Microsoft.Web/sitesdemo-func-PROD" #to fa
apis:
